name: build-xpi
on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create XPI
        run: |
          mkdir -p dist
          zip -r dist/JPMailCheckExtension.xpi . \
            -x "dist/*" \
               ".git/*" \
               ".github/*" \
               "**/.DS_Store" \
               "README.md" \
               "LICENSE"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: JPMailCheckExtension.xpi
          path: dist/JPMailCheckExtension.xpi

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: JPMailCheckExtension.xpi
          path: dist
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/JPMailCheckExtension.xpi

